Comment, UploadedMusic에 인증 및 user 정보 리팩토링 완료
Mu-necting/Mu-necting_Server_V4 pull request #54
Opened 2024-11-02 01:06 UTC by mingmingmon

📄 PR 요약
인증 로직이 완성됨에 따라 comment와 uploadedMusic에서 사용자 정보 관련 로직을 리팩토링했습니다.

📋 관련 이슈
close: #30 
🛠️ 변경 사항 설명
- comment
댓글 작성 시 @UserId를 전달 받아 사용자 정보를 DB에 저장할 수 있도록 했습니다.
댓글 조회 시 UserResponseDto를 활용해 댓글 작성자의 정보(아이디, 닉네임, 이미지)를 파악합니다. 동시에 내가 쓴 댓글인지 판별하는 필드를 추가했습니다.
- uploadedMusic
음악 업로드 시 @UserId를 전달 받아 사용자 정보를 DB에 저장할 수 있도록 했습니다.
내 주변 음악 탐색 시 UserResponseDto를 활용해 음악 업로더의 정보(아이디, 닉네임, 이미지)를 파악합니다.

📷 스크린샷
- 댓글 생성
![image](https://github.com/user-attachments/assets/36b7d77d-f939-425e-9510-001ffd10460d)
- 댓글 조회
<img width="599" alt="image" src="https://github.com/user-attachments/assets/f3f4ea7e-173a-480e-9b20-ed81a416d96b">
- 음악 업로드
![image](https://github.com/user-attachments/assets/4f66a989-4af1-498c-b2a7-a61db7462cc0)
- 업로드된 음악 조회
```
{
  "isSuccess": true,
  "code": "COMMON200",
  "message": "성공입니다.",
  "data": [
    {
      "id": 1,
      "musicResponseDto": {
        "trackId": "7Isj4vQYmlRNHZf7jyLSFh",
        "trackUri": "spotify:track:7Isj4vQYmlRNHZf7jyLSFh",
        "trackTitle": "Hello Mr. my yesterday (From 애니메이션 \"명탐정 코난\" 10기) - 한국어버젼",
        "trackPreview": "https://p.scdn.co/mp3-preview/713b0c77970014c61e3dddafe5271e9c9ef84f81?cid=345a34f068f243c59debd59a01c2802f",
        "artists": [
          {
            "artistName": "ASHGRAY",
            "artistId": "1POaEiqUMZnsV3b3N7sPsq",
            "artistUri": "spotify:artist:1POaEiqUMZnsV3b3N7sPsq",
            "images": null
          }
        ],
        "images": null
      },
      "latitude": 0,
      "longitude": 0,
      "userResponseDto": {
        "id": 1,
        "nickname": "민주",
        "imageUrl": null
      }
    },
    {
      "id": 2,
      "musicResponseDto": {
        "trackId": "7Isj4vQYmlRNHZf7jyLSFh",
        "trackUri": "spotify:track:7Isj4vQYmlRNHZf7jyLSFh",
        "trackTitle": "Hello Mr. my yesterday (From 애니메이션 \"명탐정 코난\" 10기) - 한국어버젼",
        "trackPreview": "https://p.scdn.co/mp3-preview/713b0c77970014c61e3dddafe5271e9c9ef84f81?cid=345a34f068f243c59debd59a01c2802f",
        "artists": [
          {
            "artistName": "ASHGRAY",
            "artistId": "1POaEiqUMZnsV3b3N7sPsq",
            "artistUri": "spotify:artist:1POaEiqUMZnsV3b3N7sPsq",
            "images": null
          }
        ],
        "images": null
      },
      "latitude": 0,
      "longitude": 0,
      "userResponseDto": {
        "id": 1,
        "nickname": "민주",
        "imageUrl": null
      }
    },
    {
      "id": 3,
      "musicResponseDto": {
        "trackId": "7Isj4vQYmlRNHZf7jyLSFh",
        "trackUri": "spotify:track:7Isj4vQYmlRNHZf7jyLSFh",
        "trackTitle": "Hello Mr. my yesterday (From 애니메이션 \"명탐정 코난\" 10기) - 한국어버젼",
        "trackPreview": "https://p.scdn.co/mp3-preview/713b0c77970014c61e3dddafe5271e9c9ef84f81?cid=345a34f068f243c59debd59a01c2802f",
        "artists": [
          {
            "artistName": "ASHGRAY",
            "artistId": "1POaEiqUMZnsV3b3N7sPsq",
            "artistUri": "spotify:artist:1POaEiqUMZnsV3b3N7sPsq",
            "images": null
          }
        ],
        "images": null
      },
      "latitude": 0,
      "longitude": 0,
      "userResponseDto": {
        "id": 1,
        "nickname": "민주",
        "imageUrl": null
      }
    }
  ]
}
```
확인 요청 사항
1. env 파일 내용을 알파벳 순서로 정렬했습니다! 노션 확인 부탁드려요.
2. UserId로 user를 DB에서 조회하는 로직을 메소드로 추출했습니다. 잘못된 부분이 있으면 알려주세요.

2024-11-02 12:28 UTC, mungsil requested changes

2024-11-02 12:28 UTC, mungsil commented on src/main/java/com/munecting/api/domain/comment/dto/response/CommentResponseDto.java
> +         UserResponseDto userResponseDto,
해당 필드명이 프론트엔드 개발자 분들에게 그대로 노출되는 만큼, `userResponseDto`라는 이름보다 `user` 혹은 `author`와 같은 직관적인 이름을 사용하는게 어떨까요?

2024-11-02 12:28 UTC, mungsil commented on src/main/java/com/munecting/api/domain/comment/service/CommentService.java
> +        User user = userService.findUserByIdOrThrow(userId);
`findUserByIdOrThrow`메서드로 받아오는 `user` 객체가 사용되지 않는 것으로 보여요. 또한, 유효성 검증의 목적이 잘 드러나지 않습니다. 
따라서 `validateUserExist`와 같은 메서드를 작성해주는 것은 어떨까요? 이때 `existsById`를 이용하면 불필요한 객체 조회를 방지할 수 있을 것 같아요.

2024-11-02 12:28 UTC, mungsil commented on src/main/java/com/munecting/api/domain/comment/service/CommentService.java
`getCommentsByTrackIdWithCursor` 메서드 수정 제안드립니다.
```
    @Transactional(readOnly = true)
    public Page<Comment> getCommentsByTrackIdWithCursor(String trackId, LocalDateTime cursor, Pageable pageable) {
        log.info(String.valueOf(cursor));
        return commentRepository.findCommentsByTrackIdWithCursor(trackId, cursor.toString(), pageable);
    }
```
1. `getCommentsByTrackIdWithCursor` 메서드가 `getCommentsByTrackId`에서만 사용되는 것 같아요. 따라서 접근 제어자를 `private`으로 변경해주는게 좋을 같습니다.
2. `CommentController`의 `getCommentsByTrackId`에서 `cursor` 값이 `required=false` 이므로, `null`값인 경우 별도의 처리가 필요합니다!

2024-11-02 12:28 UTC, mungsil commented on src/main/java/com/munecting/api/domain/comment/service/CommentService.java
> +                    UserResponseDto userResponseDto = UserResponseDto.of(commentWriter.getId(), commentWriter.getNickname(), commentWriter.getProfileImageUrl());
응집도와 가독성을 높이기 위해 `UserResponseDto` 생성을 `CommentResponseDto`에서 진행하면 어떨까요?

2024-11-02 12:28 UTC, mungsil commented on src/main/java/com/munecting/api/domain/uploadedMusic/service/MusicService.java
> +                    UserResponseDto userResponseDto = UserResponseDto.of(user.getId(), user.getNickname(), user.getProfileImageUrl());
응집도와 가독성을 높이기 위해 `UserResponseDto` 생성을 `UploadedMusicResponseDto`안에서 진행하면 어떨까요?

2024-11-02 12:28 UTC, mungsil commented on src/main/java/com/munecting/api/domain/user/service/UserService.java
확인했습니다! 감사합니다:)

2024-11-02 12:31 UTC, mungsil commented
댓글 삭제 및 업데이트 시, 본인 확인 로직 추가가 필요할 것 같아요. 물론 조회 쪽에서 isOwner값을 줌으로써 1차 검증이 수행되겠지만 보안적으로 서버 쪽에서 한 번 더 검증하는게 좋을 것 같습니다.

2024-11-02 12:58 UTC, mingmingmon commented on src/main/java/com/munecting/api/domain/comment/dto/response/CommentResponseDto.java
> +         UserResponseDto userResponseDto,
만약 프론트엔드 개발자분들께서 userResponseDto보다 user, author 등의 네이밍을 선호하신다면 수정을 고려할 수 있을 것 같습니다.

다만 저는 commentResponseDto 안에 user정보를 dto로 또 담아서 보낸다는 의미가 명확하게 드러나야 된다고 생각해요. 또한 user나 author 처럼 ~dto로 끝나지 않는 네이밍이라면 도메인과 헷갈리는 경우도 생길 것 같아서, 백엔드 개발자로서는 유지보수 측면에서도 ~dto 형태로 네이밍 하는 것이 더 좋아보입니다!

2024-11-02 13:07 UTC, mingmingmon commented on src/main/java/com/munecting/api/domain/comment/service/CommentService.java
1. `@Transactional(readOnly = true)`를 사용하기 위해서는 public으로 선언해주는`@Transactional(readOnly = true)`를 사용하기 위해서는 public으로 선언해주어야 합니다. 

그러나 `getCommentsByTrackIdWithCursor` 메소드는 `getCommentsByTrackId`에서만 사용하고 있기 때문에 private로 처리하고 Transaction은 `getCommentsByTrackId`에만 걸어주는 것으로 수정해도 될까요?

2. 해당 부분은 required = true로 해서 요청할 떄의 localDateTime을 무조건 받도록 하는 방향은 어떨까요? required=false로 진행하고 null일 때 백엔드 측에서 localDateTime을 now로 처리해도 되지만, 일관성 있는 api 사용을 위해서 전자로 진행하고 싶습니다.

2024-11-02 13:09 UTC, mingmingmon commented on src/main/java/com/munecting/api/domain/comment/service/CommentService.java
> +                    UserResponseDto userResponseDto = UserResponseDto.of(commentWriter.getId(), commentWriter.getNickname(), commentWriter.getProfileImageUrl());
userResponseDto의 생성을 of가 아니라 commentService 안에 메소드로 추출하는 의미일까요?

저는 userResponseDto의 경우 User 도메인의 정보를 통해 생성하는 것이기 때문에 User 패키지 아래에 위치했습니다. 그리고 dto 생성 컨벤션에 맞게 of를 사용해준 것이었어요. @mungsil 님께서 원하는 방향을 조금 더 자세히 설명해주실 수 있을까요?

2024-11-02 13:22 UTC, mingmingmon commented
댓글 수정/삭제 시 같은 로직으로 로그인한 사용자와 댓글 작성자를 비교해서 다음과 같이 예외처리 할 수 있도록 수정했습니다!

<img width="451" alt="image" src="https://github.com/user-attachments/assets/d3733b3f-7fd8-4316-b2d5-6d6f97fe2c31">

2024-11-02 13:41 UTC, mungsil commented on src/main/java/com/munecting/api/domain/comment/service/CommentService.java
1. 넵! 제안해주신 의견에 동의하는 바에며, 언급해주신대로 진행해주시면 좋을 것 같습니다.
2. 말씀해주신 방향도 괜찮은 방안으로 보입니다.  `required = true`로 변경하는 것에 동의해요.

2024-11-02 13:53 UTC, mungsil commented on src/main/java/com/munecting/api/domain/comment/service/CommentService.java
> +                    UserResponseDto userResponseDto = UserResponseDto.of(commentWriter.getId(), commentWriter.getNickname(), commentWriter.getProfileImageUrl());
제가 말씀드린 의도는 다음과 같이 `CommentResponseDto` 안에서 `UserResponseDto` 생성 로직을 포함하는 것이었습니다.
```
    public static CommentResponseDto of(User user, Comment comment, Boolean isOwner) {
        UserResponseDto userDto = UserResponseDto.of(
                user.getId(), user.getNickname(), user.getProfileImageUrl());

        return CommentResponseDto.builder()
                .userResponseDto(userDto)
                .trackId(comment.getTrackId())
                .content(comment.getContent())
                .createdAt(comment.getCreatedAt())
                .updatedAt(comment.getUpdatedAt())
                .isOwner(isOwner)
                .build();
    }
```
제가 말씀드린 방법과 사용하신 방법 모두 장단점을 가지고 있습니다. 선호하시는 방식을 알 수 있을까요?

2024-11-02 14:04 UTC, mungsil commented on src/main/java/com/munecting/api/domain/comment/dto/response/CommentResponseDto.java
> +         UserResponseDto userResponseDto,
`DTO`안에 `DTO`가 포함되어 있음을 명확히 하기 위해 지금과 같은 네이밍 방식을 사용하셨군요. 
저의 경우, 클래스명에 명시되어있는 `DTO`와 필드 타입을 통해 해당 필드가 `DTO`임을 식별할 수 있을 것이라고 생각하여 간결하게 `user`와 같은 필드명을 사용하고는 합니다. 

말씀해주신대로 `DTO`임을 표기하여 유지보수성을 높임과 동시에, 직관성을 위하여  `userDto`와 같은 이름을 사용하는 것에 대해서는 어떻게 생각하시는 지 여쭤보고 싶어요.

2024-11-03 03:13 UTC, mingmingmon commented on src/main/java/com/munecting/api/domain/comment/dto/response/CommentResponseDto.java
> +         UserResponseDto userResponseDto,
좋습니다! ~dto를 사용하지만 조금 더 간결한 방식으로 수정해보겠습니다

2024-11-03 03:16 UTC, mingmingmon commented on src/main/java/com/munecting/api/domain/comment/service/CommentService.java
> +                    UserResponseDto userResponseDto = UserResponseDto.of(commentWriter.getId(), commentWriter.getNickname(), commentWriter.getProfileImageUrl());
아하 이해했습니다! 제안해주신 방식이 User 객체를 전달 받아 commentResponseDto에서 userDto를 생성하는 것이니 의미적으로 더 적합한 것 같습니다. 수정하도록 할게요!

2024-11-03 09:11 UTC, mungsil commented on src/main/java/com/munecting/api/domain/comment/dto/response/CommentResponseDto.java
> +         UserResponseDto userResponseDto,
확인했습니다! 반영 감사합니다 :)

2024-11-03 09:12 UTC, mungsil commented on src/main/java/com/munecting/api/domain/comment/service/CommentService.java
> +                    UserResponseDto userResponseDto = UserResponseDto.of(commentWriter.getId(), commentWriter.getNickname(), commentWriter.getProfileImageUrl());
확인했습니다! 반영 감사합니당

2024-11-03 09:13 UTC, mungsil commented
모두 확인 완료했습니다! 고생하셨어용 👍

2024-11-03 09:14 UTC, mungsil approved these changes

2024-11-03 09:18 UTC, merged